### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by Wladefant** [webwhiz-ai/webwhiz#212]
# Problem
When setting up frontend after running npm run start the error below shows afer starting the development server

# Error

```bash
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/wladefant/development/chatbot-core/frontend/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/wladefant/development/chatbot-core/frontend/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/wladefant/development/chatbot-core/frontend/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/wladefant/development/chatbot-core/frontend/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/wladefant/development/chatbot-core/frontend/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/wladefant/development/chatbot-core/frontend/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/wladefant/development/chatbot-core/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/wladefant/development/chatbot-core/frontend/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.20.3
```

# Temp Solution
export NODE_OPTIONS=--openssl-legacy-provider

**Comment by La100** [comment]
You can modify your package.json in frontend
 "scripts": {
    "start": "react-scripts --openssl-legacy-provider start"
}
